service: this-my-test-service-that
# should truncate to this-my-test-service-tha-serverlessdeploymentbuck-[hash]

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello

